### PR TITLE
Add function to calculate loan amount from payment.

### PR DESCRIPTION
**Pull request by sepiariver**
**What is it?**

A clone of the `$.loanInfo` function that takes a fixed monthly payment amount instead of a principal amount, and returns the principal amount that can be borrowed based on the interest rate, term, and payments.

**Why is it needed?**

It's useful for car loan calculators where the user wishes to see how much they can afford to pay for a car, based on a how much they're willing to commit in monthly payments.

**The fine print**
The function hasn't been implemented in the jQuery plugin. It's only there as a helper function, and has a very similar signature to the existing function from which it was cloned. Note: the term "cloned" is used lightly, as the internal calculations were modified significantly to support this functionality.
Added calls to `toString()` on the `input` values before using `replace()` in order to prevent type errors.
Added radix argument to `parseInt()` calls.

### CODE REVIEW

**Comment by jpederson** [comment]
Hey @sepiariver - do you want to update your code to fix the merge conflicts I'll get if I merge it, or shall I do it? Just figured that if I do it, you won't get credit for your changes, and I like giving credit where it's due.

**Comment by sepiariver** [comment]
Thanks for the heads up! I don't mind fixing conflicts. I'll look at it later today :)

**Comment by sepiariver** [comment]
Conflicts should be fixed now @jpederson :)

**Comment by jpederson** [comment]
Thanks for the contribution!

**Pull request merged**
