### PR TITLE
feature: Add (optional) down payment to basic loan

### PR DESCRIPTION
**Pull request by mishasaggi**
Added an optional down payment field to basic loans that  #accepts absolute amounts.

basic_downpymnt

basic_downpymntval

### CODE REVIEW

**Comment by mishasaggi** [comment]
I added the logic to only the basic loan calculator, as I needed it for my project. Would be happy to extend it to other calculators if it's a feature you want to include in your library.
Please review and let me know of any changes required!

**Comment by jordan26** [comment]
Would it be possible to switch this down payment from a specific value(s) to a user define percentage? 10% instead of 3000 for example.

**Comment by mishasaggi** [comment]
Yep, been wanting to add percentages myself. Will do this weekend.

**Comment by bahiirwa** [comment]
Impressive, did this ever get merged?

**Comment by Enternik** [comment]
Подскажите, есть ли решение перевести аванс с суммы на%?

**Comment by Enternik** [comment]
Tell me, is there a solution to transfer the advance from the amount to%?

**Comment by jpederson** [comment]
I appreciate your efforts here - as a result of the new release, there are some conflicts, and I'd like to implement this myself down the line.

**Pull request closed without merging**
